name: "Test"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest ] # FIXE: Add Darwin support
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://releases.nixos.org/nix/nix-2.22.1/install
      - run: nix flake check --all-systems
      - run: nix build .#packages.x86_64-linux.allPackages 
